"""empty message

Revision ID: 22dc9400be45
Revises: 682e3b2cfef1
Create Date: 2022-09-03 14:44:27.953972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22dc9400be45'
down_revision = '682e3b2cfef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
